version: '3.5'
networks:
  deploy-guide-dev:
    driver: bridge
    
services:
  testmvc:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionString=host=postgres-container;port=5432;database=TestAspNetApp;Username=postgres;Password=toor;

  postgres_db:
    container_name: postgres-container
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: TestAspNetApp
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: